sh: fix implicit use of stat.h in arch/sh specific files
To fix:

arch/sh/drivers/dma/dma-sysfs.c:45:8: error: 'S_IRUGO' undeclared here (not in a function)
arch/sh/drivers/dma/dma-sysfs.c:75:8: error: 'S_IWUSR' undeclared here (not in a function)
make[4]: *** [arch/sh/drivers/dma/dma-sysfs.o] Error 1

drivers/sh/intc/core.c:449: error: 'S_IRUGO' undeclared here (not in a function)
make[5]: *** [drivers/sh/intc/core.o] Error 1

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
(cherry picked from commit 0c43871b4036444b8734d06ab9ec0bb9046aada4)

Conflicts:

	arch/sh/drivers/dma/dma-sysfs.c

Signed-off-by: Simon Horman <horms@verge.net.au>